name: nurlan_ustaz_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # plugins
  chewie: ^1.5.0
  clipboard: ^0.1.3
  just_audio: ^0.9.34
  share_plus: ^10.1.4
  geolocator: ^13.0.4
  url_launcher: ^6.1.11
  image_picker: ^1.1.2
  audioplayers: ^6.4.0
  video_player: ^2.7.0
  path_provider: ^2.0.15
  better_player: ^0.0.83
  webview_flutter: ^4.11.0
  qr_code_scanner: ^1.0.1
  package_info_plus: ^8.3.0
  network_info_plus: ^6.1.4
  shared_preferences: ^2.0.15
  permission_handler: ^12.0.0+1
  flutter_windowmanager: ^0.2.0
  internet_connection_checker: ^3.0.1
  flutter_local_notifications: ^19.1.0
  syncfusion_flutter_pdfviewer: ^29.1.40

  #state
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # dart
  dio: ^5.2.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  rxdart: ^0.28.0
  provider: ^6.0.5
  equatable: ^2.0.5
  auto_route: ^9.3.0+1
  injectable: ^2.1.0
  flutter_bloc: ^9.1.1
  get_ip_address: ^0.0.5
  chucker_flutter: ^1.3.5
  json_annotation: ^4.7.0
  stop_watch_timer: ^3.2.2
  pretty_dio_logger: ^1.1.1
  easy_localization: ^3.0.1
  freezed_annotation: ^3.0.0
  web_socket_channel: ^3.0.3
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

  # firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  firebase_dynamic_links: ^6.1.5

  #ui
  pinput: ^5.0.1
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.1
  # msh_checkbox: ^2.0.1
  dots_indicator: ^4.0.1
  flutter_qiblah: ^3.1.0+1
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_slidable: ^4.0.0
  dropdown_button2: ^2.3.9
  timer_button_fork: ^4.0.1
  flutter_screenutil: ^5.7.0
  audio_video_progress_bar: ^2.0.3
  flutter_widget_from_html: ^0.15.3
  mask_text_input_formatter: ^2.4.0
  # calendar_agenda: ^0.0.2+3
  calendar_agenda:
    path: ../calendar_agenda

dev_dependencies:
  flutter_test:
    sdk: flutter

  # codegen
  freezed: ^3.0.0-0.0.dev
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.1.5

  #
  change_app_package_name: ^1.1.0

  # linter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/logo/appstore.png"
  image_path: "assets/images/logo/focus.png"
  min_sdk_android: 13

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
  fonts:
    - family: SF_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf

    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-BoldItalic.ttf
        - asset: assets/fonts/Philosopher-Italic.ttf
        - asset: assets/fonts/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher-Bold.ttf
