// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEONhqAiBmGIHRcJ_PXiJam4cxxrxbl0',
    appId: '1:280448489679:android:0eabadf205f11bded7bfba',
    messagingSenderId: '280448489679',
    projectId: 'nurlanustazanalytics',
    storageBucket: 'nurlanustazanalytics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmeow6oyX2cWv1OX6oj9NiEDBKmvKdXIw',
    appId: '1:280448489679:ios:81108d4cc41893ccd7bfba',
    messagingSenderId: '280448489679',
    projectId: 'nurlanustazanalytics',
    storageBucket: 'nurlanustazanalytics.firebasestorage.app',
    iosBundleId: 'com.nurlan.ustaz.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmeow6oyX2cWv1OX6oj9NiEDBKmvKdXIw',
    appId: '1:280448489679:ios:81108d4cc41893ccd7bfba',
    messagingSenderId: '280448489679',
    projectId: 'nurlanustazanalytics',
    storageBucket: 'nurlanustazanalytics.firebasestorage.app',
    iosBundleId: 'com.nurlan.ustaz.flutter',
  );

}