// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQxX7a8fHl-mACtVzL1WHx2S2YMCPUAaQ',
    appId: '1:53340493475:web:262e866301916779f1d116',
    messagingSenderId: '53340493475',
    projectId: 'nurlanustazdev0',
    authDomain: 'nurlanustazdev0.firebaseapp.com',
    storageBucket: 'nurlanustazdev0.appspot.com',
    measurementId: 'G-ZGZ01Q17HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjL_Nhu-W4tHdcpNfWLM6DSp-wLGyzjbk',
    appId: '1:53340493475:android:8099ab2d7b1a15dff1d116',
    messagingSenderId: '53340493475',
    projectId: 'nurlanustazdev0',
    storageBucket: 'nurlanustazdev0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8T0zlVedXkzxNT0Ffj-3G6YW_bOokeE',
    appId: '1:53340493475:ios:7af6bb4e6cd7a700f1d116',
    messagingSenderId: '53340493475',
    projectId: 'nurlanustazdev0',
    storageBucket: 'nurlanustazdev0.appspot.com',
    iosBundleId: 'com.nurlan.ustaz.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8T0zlVedXkzxNT0Ffj-3G6YW_bOokeE',
    appId: '1:53340493475:ios:7af6bb4e6cd7a700f1d116',
    messagingSenderId: '53340493475',
    projectId: 'nurlanustazdev0',
    storageBucket: 'nurlanustazdev0.appspot.com',
    iosBundleId: 'com.nurlan.ustaz.flutter',
  );
}
